research:
  prospective_evaluation:
    enabled: true

    candidate:
      path: ml/research/candidates/specs/momentum_si_001/candidate_momentum_si_001.yaml

    evaluation:
      path: ml/research/candidates/specs/momentum_si_001/evaluation_candidate_momentum_si_001.yam
