from __future__ import annotations

import importlib.util
from datetime import datetime, timezone
from pathlib import Path
from typing import Any

from config import (
    DISCOVERY_DIR,
    ROOT,
    RUNS_DIR,
)
from state import read_json, write_json


def target_profile_code(
    module_name: str,
) -> str:
    return f'''"""Controlled adaptive target-profile experiment generated by AI Lab."""

from __future__ import annotations

from typing import Any


def run(
    cache,
    signal_name: str,
    direction: str,
    fraction: float,
    targets: list[str],
) -> dict[str, Any]:
    """Report every supplied target for one fixed regime.

    No target is selected by this experiment.
    Every supplied target is reported in the same deterministic order.
    """

    mask = cache.tail_masks[
        f"{{signal_name}}|{{direction}}|{{fraction}}"
    ]

    window = cache.window_masks[
        "window_2"
    ][
        "validation"
    ]

    rows = []

    for target_name in targets:
        target = cache.targets[
            target_name
        ]

        selected = (
            window
            & mask
        )

        n = int(
            selected.sum()
        )

        events = int(
            (
                target[selected] > 0
            ).sum()
        ) if n else 0

        rows.append(
            {{
                "target": target_name,
                "n": n,
                "events": events,
                "event_rate": (
                    events / n
                    if n
                    else None
                ),
            }}
        )

    return {{
        "experiment_family": "{module_name}",
        "rows": rows,
    }}
'''


def extend(
    history: list[dict[str, Any]],
    family: str,
) -> dict[str, Any]:
    DISCOVERY_DIR.mkdir(
        parents=True,
        exist_ok=True,
    )

    module_name = (
        f"adaptive_{family}_experiment"
    )

    path = (
        DISCOVERY_DIR
        / f"{module_name}.py"
    )

    if family == "target_profile":
        content = target_profile_code(
            module_name
        )
    else:
        raise ValueError(
            f"Unknown extension family: {family}"
        )

    if path.exists():
        existing = path.read_text(
            encoding="utf-8"
        )

        if existing != content:
            raise ValueError(
                "Refusing to overwrite extension code: "
                f"{path}"
            )

    else:
        path.write_text(
            content,
            encoding="utf-8",
        )

    # Validate generated source before execution.
    compile(
        path.read_text(
            encoding="utf-8"
        ),
        str(path),
        "exec",
    )

    return {
        "phase": "EXTEND",
        "family": family,
        "code_path": str(
            path.relative_to(
                ROOT
            )
        ),
        "reason": (
            "finite_parameter_space_exhausted"
        ),
        "history_count": len(
            history
        ),
    }


def execute_target_profile_extension(
    source: dict[str, Any],
    shared_session,
) -> dict[str, Any]:
    module_path = (
        DISCOVERY_DIR
        / "adaptive_target_profile_experiment.py"
    )

    module_name = (
        "blankdiss_adaptive_target_profile"
    )

    module_spec = (
        importlib.util.spec_from_file_location(
            module_name,
            module_path,
        )
    )

    if (
        module_spec is None
        or module_spec.loader is None
    ):
        raise ValueError(
            "Could not load target-profile extension."
        )

    module = (
        importlib.util.module_from_spec(
            module_spec
        )
    )

    module_spec.loader.exec_module(
        module
    )

    signals = source[
        "signals"
    ]

    signal_name = str(
        signals[0][
            "name"
        ]
    )

    direction = str(
        signals[0].get(
            "direction",
            "lower",
        )
    )

    fraction = float(
        signals[0].get(
            "bins",
            [0.20],
        )[0]
    )

    targets = [
        str(value)
        for value in source[
            "targets"
        ]
    ]

    result = module.run(
        shared_session.cache,
        signal_name,
        direction,
        fraction,
        targets,
    )

    path = (
        RUNS_DIR
        / datetime.now(
            timezone.utc
        ).strftime(
            "%Y%m%dT%H%M%S%fZ"
        )
        / "adaptive_target_profile.json"
    )

    write_json(
        path,
        result,
    )

    persisted = read_json(
        path
    )

    if persisted is None:
        raise ValueError(
            "Extension result could not be read back."
        )

    return {
        "path": str(
            path.relative_to(
                ROOT
            )
        ),
        "result": persisted,
    }
